/* ============ THE DETECTORIST — GAME DATA ============ */
'use strict';
const DATA = (() => {

// ---------- DETECTORS ----------
// cond: items carry a conductivity 0..99. Each detector maps it to its real ID scale.
const DETECTORS = {
  vanquish340: { id:'vanquish340', brand:'Meridian', name:'Drifter 340', price:0, owned:true,
    idMin:-9, idMax:40, depth:22, gold:0.15, recovery:0.8, screen:'lcd-seg',
    desc:'Entry-level multi-frequency. No numeric ID — just a 5-segment bar. You learn to listen.' },
  xterrapro: { id:'xterrapro', brand:'Meridian', name:'Terrain Pro', price:499,
    idMin:-19, idMax:99, depth:26, gold:0.2, recovery:0.9, screen:'lcd-mono',
    desc:'Rugged waterproof workhorse. Full −19 to 99 numeric ID scale and better depth.' },
  equinox900: { id:'equinox900', brand:'Meridian', name:'Solstice 900', price:1549,
    idMin:-19, idMax:99, depth:33, gold:0.35, recovery:1.2, screen:'lcd-back',
    desc:'TriWave simultaneous multi-frequency. Deep, fast recovery, stable IDs. The serious upgrade.' },
  manticore: { id:'manticore', brand:'Meridian', name:'Chimera', price:2699,
    idMin:0, idMax:99, depth:40, gold:0.45, recovery:1.5, screen:'lcd-2d',
    desc:'Flagship. 2D ID map plots ferrous against conductivity — see straight through iron falsing.' },
  goldmonster: { id:'goldmonster', brand:'AurumTech', name:'Nugget Hound 1000', price:1149,
    idMin:0, idMax:0, depth:25, gold:2.2, recovery:1.0, screen:'lcd-gold', goldOnly:true,
    desc:'45 kHz gold machine. No target ID — just a needle. Hears sub-gram nuggets VLFs miss.' },
  gpx6000: { id:'gpx6000', brand:'AurumTech', name:'DeepStrike 6000', price:7999,
    idMin:0, idMax:0, depth:60, gold:4.0, recovery:1.0, screen:'lcd-gold', goldOnly:true,
    desc:'PulseCore induction. Punches through mineralised goldfields ground to deep nuggets.' },
};
const DETECTOR_ORDER = ['vanquish340','xterrapro','equinox900','manticore','goldmonster','gpx6000'];

// ---------- TOOLS / GEAR (backpack slots) ----------
const TOOLS = {
  trowel:     { id:'trowel', name:'Plastic trowel', price:0, slots:1, dig:8,  owned:true, kind:'digger',
    desc:'Came free with the detector. Slow, but it fills the hole.' },
  lesche:     { id:'lesche', name:'Groundhog digger knife', price:90, slots:1, dig:14, kind:'digger',
    desc:'Serrated steel blade. Cuts a neat plug in turf twice as fast.' },
  spade:      { id:'spade', name:'Ironbark spade', price:120, slots:2, dig:22, kind:'digger',
    desc:'Full-size spade for fields and goldfields. Heavy — takes two pack slots.' },
  scoop:      { id:'scoop', name:'Stainless sand scoop', price:149, slots:2, dig:26, kind:'digger', beachOnly:true,
    desc:'On sand, nothing beats a scoop. Useless on turf.' },
  pinpointer: { id:'pinpointer', name:'Harrier Pin-Probe AT', price:220, slots:1, kind:'pinpointer',
    desc:'"The Parsnip." Halves your recovery time and saves your stamina in the hole.' },
  snacks:     { id:'snacks', name:'Snack pack ×3', price:12, slots:1, kind:'consumable', uses:3, restore:35,
    desc:'Muesli bars and a sandwich. Press R in the field to restore stamina.' },
  thermos:    { id:'thermos', name:'Thermos of tea', price:25, slots:1, kind:'consumable', uses:2, restore:55,
    desc:'Two strong cups. Nothing restores morale on a cold field like it.' },
  bigpack:    { id:'bigpack', name:'Field rucksack upgrade', price:180, slots:0, kind:'upgrade',
    desc:'Permanently adds 2 backpack slots.' },
};

// ---------- PERMITS ----------
const PERMITS = {
  minersRight: { id:'minersRight', name:"Miner's Right (VIC)", price:25,
    desc:'Required to fossick for gold on Crown land in Victoria. Valid for the goldfields.' },
};

// ---------- ITEMS ----------
// cond 0..99 conductivity (higher = higher tone & ID). fe = ferrous. jit = extra ID jitter.
// depth [min,max] cm. val [min,max] sale $. w = spawn weight. icon: painter key. tint: icon colour.
// kind: coin | relic | jewellery | gold | trash. bucket: bucket-list id.
const ITEMS = {
  // --- universal trash ---
  nail:      { name:'Rusty nail', kind:'trash', cond:4, fe:true, jit:3, depth:[3,25], val:[0,0], w:16, icon:'nail', tint:'#7a4a2b',
    blurb:'Square-shanked and crusty. The soundtrack of every old site.' },
  bottlecap: { name:'Rusty bottle cap', kind:'trash', cond:70, jit:20, depth:[2,12], val:[0,0], w:12, icon:'cap', tint:'#8a6a3a',
    blurb:'Reads like a coin, lies like a politician. Every detectorist digs a thousand.' },
  ringpull:  { name:'Ring pull', kind:'trash', cond:42, jit:5, depth:[2,10], val:[0,0], w:12, icon:'pull', tint:'#9aa0a6',
    blurb:'1970s-style detachable pull tab. Sits exactly where gold rings sit. Cruel.' },
  foil:      { name:'Foil scrap', kind:'trash', cond:12, jit:6, depth:[2,8], val:[0,0], w:10, icon:'foil', tint:'#b9bec4',
    blurb:'A shred of chocolate wrapper. The shallow chirp that fools no one twice.' },
  shotshell: { name:'Shotgun shell base', kind:'trash', cond:44, jit:3, depth:[3,15], val:[0,0], w:6, icon:'shell', tint:'#b08d3e',
    blurb:'Brass head of a spent 12-gauge. Fields are full of them.' },
  canslaw:   { name:'Can slaw', kind:'trash', cond:26, jit:12, depth:[2,10], val:[0,0], w:7, icon:'foil', tint:'#8f969c',
    blurb:'Aluminium can shredded by a mower. Comes out of the ground in confetti.' },
  matchbox:  { name:'Matchbox car', kind:'relic', cond:38, jit:5, depth:[4,12], val:[4,15], w:2, icon:'car', tint:'#c23b2f',
    blurb:'A 1970s die-cast racer, paint still clinging on. Somebody cried over losing this.' },
  horseshoe: { name:'Horseshoe', kind:'relic', cond:8, fe:true, jit:2, depth:[8,28], val:[5,12], w:3, icon:'shoe', tint:'#6e5643',
    blurb:'Big iron halo. Old-timers nailed them over doorways for luck.' },
  // --- AU decimal ---
  au2d:  { name:'$2 coin', kind:'coin', c:'AU', cond:42, depth:[2,10], val:[2,2], w:8, icon:'coin', tint:'#c9a227',
    blurb:'Aluminium bronze, 1988 onward. Beer money.' },
  au1d:  { name:'$1 coin', kind:'coin', c:'AU', cond:50, depth:[2,10], val:[1,1], w:8, icon:'coin', tint:'#c9a227',
    blurb:'Mob of roos on the reverse. Adds up over a season.' },
  au50c: { name:'50c coin', kind:'coin', c:'AU', cond:74, depth:[2,12], val:[0.5,0.5], w:5, icon:'coin12', tint:'#b9bec4',
    blurb:'The big dodecagon. Unmistakable thump in the headphones.' },
  au20c: { name:'20c coin', kind:'coin', c:'AU', cond:70, depth:[2,12], val:[0.2,0.2], w:6, icon:'coin', tint:'#b9bec4',
    blurb:'Platypus reverse, cupro-nickel.' },
  // --- AU pre-decimal ---
  aupenny: { name:'Penny (1911–64)', kind:'coin', c:'AU', cond:50, depth:[8,24], val:[2,10], w:6, icon:'coin', tint:'#8a5a30',
    blurb:'Big bronze penny with the leaping kangaroo. The bread-and-butter Australian park find.' },
  auhalf:  { name:'Halfpenny', kind:'coin', c:'AU', cond:47, depth:[8,22], val:[2,8], w:4, icon:'coin', tint:'#8a5a30',
    blurb:'Penny’s little brother. Often worn slick from pocket change days.' },
  authree: { name:'Threepence (silver)', kind:'coin', c:'AU', cond:40, depth:[6,20], val:[4,15], w:4, icon:'coin', tint:'#cfd4d9',
    blurb:'Tiny sterling silver "trey". Sweet high chirp, easy to miss in the plug.' },
  ausix:   { name:'Sixpence (silver)', kind:'coin', c:'AU', cond:64, depth:[6,22], val:[6,20], w:3, icon:'coin', tint:'#cfd4d9',
    blurb:'92.5% silver until 1945. Comes up grey, wipes to a shine.' },
  aushil:  { name:'Shilling (silver)', kind:'coin', c:'AU', cond:67, depth:[8,24], val:[10,30], w:2.5, icon:'coin', tint:'#cfd4d9',
    blurb:'Ram’s head reverse. A proper silver thump.' },
  auflorin:{ name:'Florin (silver)', kind:'coin', c:'AU', cond:77, depth:[8,26], val:[8,30], w:1.5, icon:'coin', tint:'#cfd4d9',
    blurb:'The big Australian silver — two shillings of sterling. Park detecting royalty.' },
  sovereign:{ name:'Gold sovereign', kind:'coin', c:'AU', cond:53, depth:[12,30], val:[750,900], w:0.12, icon:'coin', tint:'#ffd24a', bucket:'sovereign', rare:true,
    blurb:'22ct gold, 7.98 g, St George slaying the dragon. Minted in Sydney, Melbourne and Perth. The find of a lifetime.' },
  colbutton:{ name:'Colonial button', kind:'relic', c:'AU', cond:36, depth:[8,24], val:[5,25], w:3, icon:'button', tint:'#a08b4f',
    blurb:'Flat brass button, hand-stamped backmark. Dropped off a settler’s coat 150 years ago.' },
  pickhead: { name:'Miner’s pick head', kind:'relic', c:'AU', cond:10, fe:true, depth:[10,35], val:[15,40], w:2, icon:'pick', tint:'#6e5643',
    blurb:'Hand-forged pick head from the rush days. Some digger swung this for his fortune.' },
  // --- AU beach jewellery ---
  ring9ct:  { name:'9ct gold ring', kind:'jewellery', cond:52, depth:[4,20], val:[80,180], w:1.2, icon:'ring', tint:'#e8b64c',
    blurb:'Plain 9ct band, hallmarked inside. Low, soft tone — right in pull-tab territory. You dug it anyway.' },
  ring18ct: { name:'18ct diamond ring', kind:'jewellery', cond:48, jit:6, depth:[5,22], val:[900,1600], w:0.15, icon:'gem', tint:'#ffd24a', bucket:'diamondring', rare:true,
    blurb:'18ct band, half-carat solitaire. Somewhere, someone is still sick about losing this.' },
  silchain: { name:'Silver chain', kind:'jewellery', cond:16, jit:8, depth:[3,12], val:[15,45], w:2, icon:'chain', tint:'#cfd4d9',
    blurb:'Fine sterling chain. Barely sounds off — chains read as a whisper.' },
  sinker:   { name:'Lead sinker', kind:'trash', cond:38, depth:[4,18], val:[0,0.5], w:8, icon:'drop', tint:'#5d6066',
    blurb:'Snapper lead. Beaches eat fishing gear for breakfast.' },
  earring:  { name:'Gold earring', kind:'jewellery', cond:14, jit:4, depth:[3,10], val:[30,70], w:1.5, icon:'ring', tint:'#e8b64c',
    blurb:'Single 9ct hoop. Its twin is in a jewellery box somewhere, lonely.' },
  // --- goldfields ---
  nug05: { name:'Gold nugget 0.6 g', kind:'gold', cond:9, jit:2, depth:[5,20], val:[70,95], w:4, icon:'nug', tint:'#ffd24a', goldOnly:true,
    blurb:'A sassy little picker. Sub-gram gold — the Nugget Hound’s bread and butter.' },
  nug3:  { name:'Gold nugget 3.2 g', kind:'gold', cond:15, jit:2, depth:[10,35], val:[380,480], w:1.2, icon:'nug', tint:'#ffd24a', goldOnly:true,
    blurb:'A proper crunchy nugget with character. This is why people move to the Triangle.' },
  nug12: { name:'Gold nugget 12 g', kind:'gold', cond:24, depth:[20,55], val:[1500,1900], w:0.18, icon:'nug', tint:'#ffd24a', bucket:'bignugget', rare:true, goldOnly:true,
    blurb:'Twelve grams of Victorian gold, still wearing red clay. Your hands are shaking.' },
  specimen: { name:'Quartz-gold specimen', kind:'gold', cond:12, jit:4, depth:[15,40], val:[200,420], w:0.6, icon:'quartz', tint:'#e8e2d4', goldOnly:true,
    blurb:'Gold veined through ironstone quartz. Worth more as a specimen than melt.' },
  // --- UK ---
  romanae:  { name:'Roman bronze (sestertius)', kind:'coin', c:'UK', cond:40, jit:5, depth:[12,32], val:[25,90], w:2.5, icon:'coinrough', tint:'#7d8a5a',
    blurb:'Second-century bronze, green with patina. An emperor’s face under your thumb.' },
  denarius: { name:'Roman silver denarius', kind:'coin', c:'UK', cond:30, depth:[12,30], val:[120,350], w:0.5, icon:'coinrough', tint:'#cfd4d9', bucket:'denarius', rare:true,
    blurb:'A legionary’s day’s pay, lost on a Suffolk field 1,800 years ago. Record it with the FLO.' },
  hammered: { name:'Hammered penny (Edward I)', kind:'coin', c:'UK', cond:25, depth:[10,28], val:[60,220], w:0.6, icon:'coinrough', tint:'#cfd4d9', bucket:'hammered', rare:true,
    blurb:'Wafer-thin medieval silver, struck by hand c.1300. The sound every UK detectorist chases.' },
  halfgroat:{ name:'Hammered halfgroat', kind:'coin', c:'UK', cond:20, depth:[10,26], val:[40,120], w:0.8, icon:'coinrough', tint:'#cfd4d9',
    blurb:'Clipped and worn Tudor silver. Someone’s beer money in 1560.' },
  cartwheel:{ name:'Cartwheel penny 1797', kind:'coin', c:'UK', cond:84, depth:[12,30], val:[25,80], w:1, icon:'coinbig', tint:'#8a5a30', bucket:'cartwheel', rare:true,
    blurb:'An ounce of Boulton’s copper. Slams the top of the ID scale like nothing else.' },
  vicpenny: { name:'Victorian penny', kind:'coin', c:'UK', cond:50, depth:[8,24], val:[3,15], w:5, icon:'coin', tint:'#8a5a30',
    blurb:'Bun-head or veiled head. The staple of every English pasture.' },
  ukshil:   { name:'Milled shilling', kind:'coin', c:'UK', cond:66, depth:[8,24], val:[8,35], w:3, icon:'coin', tint:'#cfd4d9',
    blurb:'Georgian or Victorian sterling. Honest silver from honest ground.' },
  musket:   { name:'Musket ball', kind:'relic', c:'UK', cond:36, depth:[8,26], val:[2,8], w:6, icon:'ball', tint:'#5d6066',
    blurb:'Squashed lead sphere. Could be Civil War, could be a poacher’s miss.' },
  buckle:   { name:'Georgian shoe buckle', kind:'relic', c:'UK', cond:30, jit:4, depth:[10,26], val:[15,60], w:2, icon:'buckle', tint:'#a08b4f',
    blurb:'Ornate brass, half its silvering gone. Fashion casualty of the 1700s.' },
  livery:   { name:'Livery button', kind:'relic', c:'UK', cond:32, depth:[8,22], val:[5,30], w:3, icon:'button', tint:'#b08d3e',
    blurb:'Gilt crest of some grand estate. The gamekeeper’s coat gave it up.' },
  posyring: { name:'Gold posy ring', kind:'jewellery', c:'UK', cond:26, depth:[12,28], val:[1800,3200], w:0.08, icon:'ring', tint:'#ffd24a', bucket:'posyring', rare:true,
    blurb:'17th-century gold, engraved inside: "You & I will lovers die". Potential Treasure — declare it.' },
  leadtoken:{ name:'Lead trade token', kind:'relic', c:'UK', cond:34, depth:[8,22], val:[3,12], w:3, icon:'coinrough', tint:'#5d6066',
    blurb:'Crude stamped disc — farm wages or tavern credit, three centuries old.' },
  // --- US ---
  indianhead:{ name:'Indian Head cent', kind:'coin', c:'US', cond:56, depth:[8,24], val:[4,25], w:4, icon:'coin', tint:'#8a5a30',
    blurb:'1859–1909 bronze. The classic American old-park find.' },
  wheatie:  { name:'Wheat cent', kind:'coin', c:'US', cond:58, depth:[5,18], val:[0.5,3], w:7, icon:'coin', tint:'#8a5a30',
    blurb:'Lincoln wheat-ears cent. "Wheaties" mean older coins are near.' },
  mercdime: { name:'Mercury dime', kind:'coin', c:'US', cond:62, depth:[6,22], val:[5,25], w:2.5, icon:'coin', tint:'#cfd4d9', bucket:'mercdime', rare:true,
    blurb:'Winged Liberty silver, 1916–45. That crisp dime tone US diggers dream about.' },
  barberq:  { name:'Barber quarter', kind:'coin', c:'US', cond:76, depth:[8,26], val:[15,60], w:1, icon:'coin', tint:'#cfd4d9',
    blurb:'Pre-1916 silver quarter, worn nearly slick. Deep, sweet and solid.' },
  buffnick: { name:'Buffalo nickel', kind:'coin', c:'US', cond:31, depth:[6,20], val:[1,8], w:3, icon:'coin', tint:'#9aa0a6',
    blurb:'Bison on the back, date usually worn away. Reads down with the gold rings.' },
  largecent:{ name:'Large cent', kind:'coin', c:'US', cond:84, depth:[12,28], val:[20,80], w:0.8, icon:'coinbig', tint:'#8a5a30',
    blurb:'Big early-1800s copper the size of a half dollar. Colonial-era ground confirmed.' },
  colonial: { name:'Colonial copper', kind:'coin', c:'US', cond:70, jit:6, depth:[14,30], val:[60,250], w:0.3, icon:'coinrough', tint:'#7d8a5a', bucket:'colonial', rare:true,
    blurb:'A 1780s state copper, corroded but readable. Proof the old tavern stood here.' },
  minie:    { name:'Civil War minié ball', kind:'relic', c:'US', cond:38, depth:[10,28], val:[3,15], w:4, icon:'ball', tint:'#5d6066',
    blurb:'Three-ring .58 calibre. History you can hold, heavier than it looks.' },
  usbutton: { name:'US Army eagle button', kind:'relic', c:'US', cond:34, depth:[10,26], val:[15,70], w:1.5, icon:'button', tint:'#b08d3e', bucket:'eaglebutton', rare:true,
    blurb:'Brass eagle "I" button — infantry, mid-1800s. Shank intact.' },
  cladq:    { name:'Clad quarter', kind:'coin', c:'US', cond:72, depth:[2,10], val:[0.35,0.35], w:8, icon:'coin', tint:'#b9bec4',
    blurb:'Modern cupro-nickel Washington. Gas money.' },
  silring:  { name:'Silver ring', kind:'jewellery', cond:20, depth:[4,16], val:[20,60], w:1.5, icon:'ring', tint:'#cfd4d9',
    blurb:'Sterling band, size L. Beaches trade in lost rings.' },
};

// ---------- BUCKET LIST ----------
const BUCKET = [
  { id:'sovereign',  item:'sovereign',  label:'Dig a gold sovereign',            where:'Australian parks & goldfields' },
  { id:'bignugget',  item:'nug12',      label:'Unearth a 10 g+ gold nugget',     where:'Victorian goldfields' },
  { id:'diamondring',item:'ring18ct',   label:'Rescue a diamond ring',           where:'Any beach' },
  { id:'denarius',   item:'denarius',   label:'Find a Roman silver denarius',    where:'English farmland' },
  { id:'hammered',   item:'hammered',   label:'Dig hammered medieval silver',    where:'English farmland' },
  { id:'cartwheel',  item:'cartwheel',  label:'Haul out a 1797 cartwheel penny', where:'English farmland & greens' },
  { id:'mercdime',   item:'mercdime',   label:'Pop a Mercury dime',              where:'American parks' },
  { id:'colonial',   item:'colonial',   label:'Prove colonial ground — 1700s copper', where:'New England parks' },
  { id:'eaglebutton',item:'usbutton',   label:'Recover a Civil War eagle button', where:'American parks' },
  { id:'posyring',   item:'posyring',   label:'The dream: a gold posy ring',     where:'English farmland' },
];

// ---------- SITES ----------
// find tables reference ITEMS keys with multiplier on base weight (1 = base).
const SITES = {
  au_park: { id:'au_park', country:'AU', flag:'🇦🇺', name:'Federation Park', region:'Sydney, NSW',
    travel:{ mode:'walk', cost:0, label:'Walk from home' },
    terrain:'park', time:'afternoon', targets:120,
    desc:'Your local park since 1901. Mown kikuyu over old picnic ground — pre-decimal silver under the fig trees.',
    finds:{ au2d:1, au1d:1, au50c:1, au20c:1, aupenny:1, auhalf:1, authree:1, ausix:1, aushil:1, auflorin:1, sovereign:0.5, colbutton:0.7, matchbox:1, nail:1, bottlecap:1, ringpull:1, foil:1, canslaw:1 },
    hazards:['karen','ranger','magpie'],
    prohibited:{ label:'War Memorial precinct', reason:'Detecting is prohibited around the memorial. Rangers patrol it.' } },
  au_beach: { id:'au_beach', country:'AU', flag:'🇦🇺', name:'Kingfisher Beach', region:'NSW South Coast',
    travel:{ mode:'bus', cost:15, label:'Bus — 2 hrs' },
    terrain:'beach', time:'sunrise', targets:110,
    desc:'Low tide at first light: rolling swell, wet sand laid bare, and the towel line seeded with a summer of losses.',
    finds:{ au2d:1.2, au1d:1.2, au50c:1, ring9ct:1, ring18ct:1, silchain:1, earring:1, sinker:1.4, bottlecap:0.8, ringpull:1.4, foil:1, cladq:0 },
    hazards:['karen','seagull'],
    soft:'drysand',
    prohibited:{ label:'Dune revegetation zone', reason:'Fenced dune rehab area. Council fines for entry.' } },
  au_gold: { id:'au_gold', country:'AU', flag:'🇦🇺', name:'Golden Gully', region:'Golden Triangle, VIC',
    travel:{ mode:'train', cost:60, label:'Train + lift — overnight' },
    terrain:'goldfields', time:'harshnoon', targets:90,
    permit:'minersRight',
    desc:'Ironbark, red clay and 160-year-old shafts. Mineralised ground that laughs at coin machines — bring a gold detector.',
    finds:{ nug05:1, nug3:1, nug12:1, specimen:1, sovereign:0.35, pickhead:1, horseshoe:1, colbutton:0.6, nail:1.4, shotshell:1, ausix:0.3 },
    hazards:['snake','ranger'],
    mineralised:true,
    prohibited:{ label:'Historic mine shafts', reason:'Unsafe shafts, heritage-protected workings. Keep out.' } },
  uk_farm: { id:'uk_farm', country:'UK', flag:'🇬🇧', name:'Wheatfield Farm', region:'Suffolk, England',
    travel:{ mode:'flight', cost:1400, label:'Flight SYD→LHR + hire car' },
    terrain:'farm', time:'cloudy', targets:130,
    permission:'farmer',
    desc:'Stubble and plough over a Roman road line. Farmer Giles wants a knock on the door — and a fair split.',
    finds:{ romanae:1, denarius:1, hammered:1, halfgroat:1, cartwheel:1, vicpenny:1, ukshil:1, musket:1.2, buckle:1, livery:1, leadtoken:1, posyring:1, nail:1.3, shotshell:1.2, canslaw:0.5 },
    hazards:['tractor'],
    soft:'plough' },
  uk_green: { id:'uk_green', country:'UK', flag:'🇬🇧', name:'Nettlebury Green', region:'Suffolk, England',
    travel:{ mode:'bus', cost:20, label:'Local bus — 40 min', requiresCountry:'UK' },
    terrain:'green', time:'morning', targets:100,
    desc:'A village green with a Norman church and five centuries of fairs, markets and dropped change.',
    finds:{ vicpenny:1.3, ukshil:1, cartwheel:0.7, halfgroat:0.5, hammered:0.4, livery:1, buckle:0.8, leadtoken:1, foil:1, ringpull:1, bottlecap:1, nail:1 },
    hazards:['karen'],
    prohibited:{ label:'Churchyard', reason:'Consecrated ground. Absolutely no detecting.' } },
  us_park: { id:'us_park', country:'US', flag:'🇺🇸', name:'Liberty Park', region:'New England, USA',
    travel:{ mode:'flight', cost:1600, label:'Flight → Boston + drive' },
    terrain:'uspark', time:'goldenhour', targets:120,
    desc:'Elm-lined common on a 1770s tavern site. Wheaties on top, colonial coppers in the subsoil.',
    finds:{ cladq:1.2, wheatie:1.2, indianhead:1, mercdime:1, barberq:0.8, buffnick:1, largecent:0.6, colonial:1, minie:1, usbutton:1, nail:1.2, bottlecap:1, ringpull:1, foil:1 },
    hazards:['karen','ranger'],
    prohibited:{ label:'Bandstand heritage lawn', reason:'Historic register lawn — city ordinance, no digging.' } },
  us_beach: { id:'us_beach', country:'US', flag:'🇺🇸', name:'Cape Wesset Beach', region:'Massachusetts, USA',
    travel:{ mode:'bus', cost:25, label:'Regional bus — 90 min', requiresCountry:'US' },
    terrain:'beach', time:'dusk', targets:100,
    desc:'Cold Atlantic surf and a boardwalk crowd. Silver rings in the wet sand, clad by the bucketful.',
    finds:{ cladq:1.6, mercdime:0.5, silring:1, ring9ct:0.8, ring18ct:0.7, silchain:1, sinker:1.2, ringpull:1.3, bottlecap:1, foil:1 },
    hazards:['seagull','karen'],
    soft:'drysand' },
  au_show: { id:'au_show', country:'AU', flag:'🇦🇺', name:'Boolara Showground', region:'Central West, NSW',
    travel:{ mode:'bus', cost:25, label:'Bus — 4 hrs' },
    terrain:'park', time:'goldenhour', targets:120,
    desc:'Country showground since 1888. A century of sideshows, wood-chops and dropped change under the kikuyu.',
    finds:{ aupenny:1.6, auhalf:1.2, authree:1.3, ausix:1, aushil:0.9, auflorin:0.8, sovereign:0.7, colbutton:1, matchbox:1.4, horseshoe:1.2, au2d:0.5, au1d:0.5, nail:1.2, bottlecap:1.2, ringpull:1, foil:1, shotshell:0.6 },
    hazards:['karen','ranger','magpie'],
    prohibited:{ label:'Heritage grandstand', reason:'The 1902 grandstand precinct is heritage listed. No digging.' } },
  uk_pasture: { id:'uk_pasture', country:'UK', flag:'🇬🇧', name:'Sheepwash Pasture', region:'Suffolk, England',
    travel:{ mode:'bus', cost:15, label:'Lane walk — 20 min', requiresCountry:'UK' },
    terrain:'pasture', time:'morning', targets:120,
    desc:'Ancient sheep pasture on the medieval fair site — never ploughed, never detected. Giles put in a word with his neighbour.',
    finds:{ hammered:1.6, halfgroat:1.4, denarius:0.5, romanae:0.7, cartwheel:0.8, vicpenny:1, ukshil:0.9, buckle:1.2, livery:1, leadtoken:1.2, musket:1, posyring:1, nail:1, bottlecap:0.6, foil:0.6 },
    hazards:['karen'] },
  us_battle: { id:'us_battle', country:'US', flag:'🇺🇸', name:'Cedar Run Field', region:'Virginia, USA',
    travel:{ mode:'bus', cost:40, label:'Drive — 2 hrs', requiresCountry:'US' },
    terrain:'pasture', time:'dusk', targets:120,
    desc:'An 1862 skirmish line on private pasture, written permission in your pocket. The ground still hums with lead.',
    finds:{ minie:2.2, usbutton:1.6, buckle:1, largecent:0.6, colonial:0.35, indianhead:0.7, wheatie:0.5, horseshoe:1.2, shotshell:1, nail:1.6, canslaw:0.5 },
    hazards:['ranger'],
    prohibited:{ label:'Soldiers’ cairn', reason:'The burial cairn is protected ground. Absolutely no digging.' } },
};
const SITE_ORDER = ['au_park','au_beach','au_gold','au_show','uk_farm','uk_green','uk_pasture','us_park','us_beach','us_battle'];

// ---------- MISSIONS ----------
const MISSIONS = [
  { id:'ring_sarah', site:'au_beach', title:'The Engagement Ring',
    post:'"Lost my engagement ring near the third dune marker on Saturday. White gold, half-carat. Reward — please help. — Sarah"',
    targetItem:'ring18ct', zone:'dunes', reward:600, rep:2,
    accept:'Sarah marks the spot on your map: near the dune fence, dry sand.',
    done:'Sarah bursts into tears and hugs you. The reward is yours — and the story is better than the money.' },
  { id:'badge_jack', site:'au_park', title:'Old Jack’s Service Badge',
    post:'"My father lost his Rising Sun badge at the 1963 Anzac picnic, near the big fig. It would mean the world. — Jack, RSL sub-branch"',
    targetItem:'colbutton', zone:'bigfig', reward:250, rep:2, renameFind:'Rising Sun badge (1963)',
    accept:'Jack shakes your hand. "Near the big fig. Dad never forgave himself."',
    done:'Jack holds the badge a long time before he speaks. The sub-branch passes a hat around for you.' },
  { id:'half_sov', site:'uk_farm', title:'The Ploughed Half Sovereign',
    post:'"Grandfather lost a half sovereign ploughing the top paddock in 1951. Find it and we’ll waive the split on everything else this trip. — G. Giles"',
    targetItem:'sovereign', zone:'topfield', reward:400, rep:2, renameFind:'Half sovereign (1951)',
    accept:'Giles points up the hill. "Top paddock. He walked that furrow line a hundred times looking."',
    done:'Giles turns the little coin over twice. "Well I’ll be damned." No split this trip — and a standing invitation.' },
  { id:'tavern_proof', site:'us_park', title:'Prove the Tavern',
    post:'"The historical society will pay for physical proof of the 1770s Sun Tavern — any colonial-era coin from the park. — Prof. E. Whitcomb"',
    targetItem:'colonial', zone:null, reward:500, rep:2,
    accept:'Whitcomb adjusts her glasses. "Anything pre-1800. Context photos, please."',
    done:'"Extraordinary." The society newsletter runs your find on the front page.' },
];

// ---------- DIALOGUE ----------
const DIALOGUE = {
  karen: {
    title:'A concerned citizen approaches',
    icon:'karen',
    lines:[ '"Excuse me! EXCUSE ME! You can’t just dig holes in a public park!"',
            '"Is that even LEGAL? I’m ringing the council right now."',
            '"I’ve got you on video, sweetheart. This is going on the community Facebook page."' ],
    options:[
      { key:'polite', label:'Explain politely & show your tidy plug', hint:'Best with good reputation',
        success:'You show her the neat plug, the filled holes, the pocketed rubbish. She deflates. "Well... I suppose someone has to pick up the ring pulls." She leaves you to it.',
        fail:'She listens with arms folded, unconvinced, and stands over you for twenty minutes narrating to her phone. Exhausting.', stam:-10 },
      { key:'permit', label:'Show your permit / permission', needs:'permitHere',
        success:'You produce the paperwork. She photographs it, finds nothing to object to, and leaves in search of an unattended dog.',
        fail:'You have nothing to show. She smells blood. "I KNEW it."', callRanger:true },
      { key:'ignore', label:'Smile, wave, keep swinging', risky:true,
        success:'You give a cheery wave and keep gridding. Denied a reaction, she films a sign instead and drifts off.',
        fail:'Ten minutes later a ranger ute pulls up. She points at you the whole way over.', callRanger:true },
      { key:'packup', label:'Tip your hat and move to another spot',
        success:'Not worth the drama. You wander 200 metres off. Ten minutes of daylight lost, zero blood pressure gained.', stam:-4, moveAway:true },
    ] },
  ranger: {
    title:'Council Ranger',
    icon:'ranger',
    finePark: 120, fineGold: 180,
    ok:'"Detecting, eh? Fill your holes, take your rubbish, stay clear of the memorial and we’ve got no problem." He gives you a nod and moves on.',
    warn:'"Mate, you were flagged near the restricted area. One warning. Won’t be two."',
    fineMsg:'"That area’s protected. I’m issuing an infringement." He writes you up.',
    noPermit:'"Fossicking here needs a Miner’s Right, mate. That’s a fine — get one online, it’s twenty-five bucks."' },
  farmer: {
    title:'Farmhouse door — Farmer Giles',
    icon:'farmer',
    intro:'A weathered man answers, wiping his hands. "Detecting, is it? Had a club out here in the nineties. What’s your offer?"',
    options:[
      { key:'split', label:'Offer a 50/50 split on anything valuable',
        result:'"Fair’s fair." He shakes on it. "Stay off the winter wheat, shut the gates, and I want to see the good stuff." Permission granted — half of UK farm sale value goes to Giles.' },
      { key:'cash', label:'Offer $80 for the day’s access',
        result:'He pockets it. "Top and bottom paddock, keep clear of the sheep. Anything Treasure-grade, we talk." Permission granted — you keep what you find.' },
      { key:'charm', label:'Talk history — the Roman road, the aerial photos', needsRep:3,
        result:'His eyebrows lift. "You’ve done your homework." He fetches a shoebox of finds from the mantel. Permission granted, no split — and he marks an X on your map.',
        failResult:'"Everyone’s an expert." He’s heard it all before. Offer money or a split.' },
    ] },
  seagull:'A seagull the size of a corgi lands on your kit and makes off with a muesli bar.',
  magpie:'SWOOP! A magpie clips your ear at speed. It’s nesting season and you’re on his lawn.',
  snake:'A tiger snake pours itself out of the grass by your dig hole. You back away very, very slowly.',
  tractor:'The tractor swings up the headland. You stand well clear and give the driver a wave.' };

// ---------- SHOP / SELLING ----------
const SELL_NOTES = {
  coin:'The coin dealer squints through a loupe, quotes book price minus his margin.',
  relic:'The curio dealer likes a story with provenance.',
  jewellery:'The jeweller weighs it, tests it, pays scrap-plus.',
  gold:'The gold buyer quotes spot price on the spot.',
  trash:'Worthless — but binning it keeps the parks open to detectorists.' };

return { DETECTORS, DETECTOR_ORDER, TOOLS, PERMITS, ITEMS, BUCKET, SITES, SITE_ORDER, MISSIONS, DIALOGUE, SELL_NOTES };
})();
